'''
--- Day 8: Resonant Collinearity ---
You find yourselves on the roof of a top-secret Easter Bunny installation.

While The Historians do their thing, you take a look at the familiar huge antenna. Much to your surprise, it seems to have been reconfigured to emit a signal that makes people 0.1% more likely to buy Easter Bunny brand Imitation Mediocre Chocolate as a Christmas gift! Unthinkable!

Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific frequency indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
The signal only applies its nefarious effect at specific antinodes based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

So, for these two antennas with frequency a, they create the two antinodes marked with #:

..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........
Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......A...
..........
..........
The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.
Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?
'''


def make_map(contents):
    return [line for line in contents.split('\n') if line]

def num_unique_antinode_locations(map):
    antinode_locations = set([])
    frequencies = get_frequencies(map)
    for frequency in frequencies:
        print('FREQUENCY: ', frequency)
        antenna_pairs = get_antenna_pairs(map, frequency)
        for antenna_pair in antenna_pairs:
            print(antenna_pair)
            antinodes = calculate_antinode_coords_for_antenna_pair(antenna_pair)
            for antinode in antinodes:
                if is_on_map(map, antinode):
                    antinode_locations.add(antinode)
        print()
    return len(antinode_locations)

def get_frequencies(map):
    frequencies = set([])
    for i in range(len(map)):
        for j in range(len(map[i])):
            if map[i][j] != '.':
                frequencies.add(map[i][j])
    return frequencies

def get_antenna_pairs(map, frequency):
    antennas = get_all_antennas_for_frequency(map, frequency)
    pairs = set([])
    for a in antennas:
        for b in antennas:
            if a != b and (b, a) not in pairs:
                pairs.add((a, b))
    return pairs

def get_all_antennas_for_frequency(map, frequency):
    antennas = set([])
    for i in range(len(map)):
        for j in range(len(map[i])):
            if map[i][j] == frequency:
                antennas.add((i, j))
    return antennas

def calculate_antinode_coords_for_antenna_pair(antenna_pair):
    a, b = antenna_pair
    i_diff = b[0] - a[0]
    j_diff = b[1] - a[1]
    return [(a[0] - i_diff, a[1] - j_diff), (b[0] + i_diff, b[1] + j_diff)]

def is_on_map(map, antinode):
    i, j = antinode
    return (0 <= i < len(map)) and (0 <= j < len(map[i]))


if __name__ == '__main__':
    with open('8/day_8_test.txt', 'r') as f:
        contents = f.read()

    map = make_map(contents)
    num = num_unique_antinode_locations(map)
    print(num)
